exp_name: clip_ft_raw_data
data_root: ./dataset
pretrained_clip_path: ../huggingface_models/openai--clip-vit-base-patch16
seed: 0
learning_rate: 1.0e-05
train_batch_size: 32
val_batch_size: 100
num_workers: 96
max_train_steps: 1000
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1.0e-03
adam_epsilon: 1.0e-08
num_warmup_steps: 100
last_epoch: -1
max_grad_norm: 1.0
mixed_precision: fp16
gradient_accumulation_steps: 1
checkpointing_step_interv: 100
validation_step_interv: 100
resume_from_checkpoint: latest
output_dir: ./output