exp_name: clip_ft_full_all
data_root: ./dataset
pretrained_clip_path: ../huggingface_models/openai--clip-vit-base-patch16
use_lora: False
pretrained_lora_path: null
lora_config: null
seed: 0
train_split: train_all
learning_rate: 5.0e-06
train_batch_size: 128
val_batch_size: 500
num_workers: 16
max_train_steps: 10000
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1.0e-03
adam_epsilon: 1.0e-08
scheduler_type: cosine
num_warmup_steps: 100
max_grad_norm: 1.0
mixed_precision: fp16
gradient_accumulation_steps: 1
checkpointing_step_interv: 1000
validation_step_interv: 1000
resume_from_checkpoint: null
output_dir: ./output
